export {default as BackgroundImg}  from './bg.png'
export {default as IndexPhone}  from './screen-n-overlay.png'
export {default as Phone1}  from './phone1.png'
export {default as TopUp}  from './Topup.png'
export {default as CreateBudget}  from './Createbudget.png'
export {default as Processing}  from './Processing.png'
export {default as FeatureBg}  from './featurebg.png'